Add debug to static.yml

diff --git a/.github/workflows/static.yml b/.github/workflows/static.yml
--- a/.github/workflows/static.yml
+++ b/.github/workflows/static.yml
@@ -33,6 +33,14 @@ jobs:
         uses: actions/checkout@v4
       - name: Setup Pages
         uses: actions/configure-pages@v5
+      - name: Check for Symlinks
+        run: |
+          if find ./public -type l | read; then
+            echo "Error: Symlinks found in ./public" >&2
+            exit 1
+          fi
+      - name: Report Artifact Size
+        run: du -sh ./public
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
